version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop-container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start-container.sh
      timeout: 300
      runas: root